[2022-08-31 22:35:31,778] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T22:35:25.115881+00:00 [queued]>
[2022-08-31 22:35:31,810] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T22:35:25.115881+00:00 [queued]>
[2022-08-31 22:35:31,814] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 22:35:31,821] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-31 22:35:31,824] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-31 22:35:31,879] {taskinstance.py:1397} INFO - Executing <Task(BashOperator): load_seed_data_once> on 2022-08-31 22:35:25.115881+00:00
[2022-08-31 22:35:31,892] {standard_task_runner.py:52} INFO - Started process 1590 to run task
[2022-08-31 22:35:31,985] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', '1_init_once_seed_data', 'load_seed_data_once', 'manual__2022-08-31T22:35:25.115881+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/init.py', '--cfg-path', '/tmp/tmp0595cnl_', '--error-file', '/tmp/tmpwfs8sxaj']
[2022-08-31 22:35:31,990] {standard_task_runner.py:80} INFO - Job 3: Subtask load_seed_data_once
[2022-08-31 22:35:32,435] {task_command.py:371} INFO - Running <TaskInstance: 1_init_once_seed_data.load_seed_data_once manual__2022-08-31T22:35:25.115881+00:00 [running]> on host 1b3d1bb2039d
[2022-08-31 22:35:34,758] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=1_init_once_seed_data
AIRFLOW_CTX_TASK_ID=load_seed_data_once
AIRFLOW_CTX_EXECUTION_DATE=2022-08-31T22:35:25.115881+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-31T22:35:25.115881+00:00
[2022-08-31 22:35:34,766] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-08-31 22:35:34,770] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'cd /dbt && dbt seed --profiles-dir .']
[2022-08-31 22:35:34,914] {subprocess.py:85} INFO - Output:
[2022-08-31 22:35:48,827] {subprocess.py:92} INFO - [0m22:35:48  Running with dbt=1.2.1
[2022-08-31 22:35:52,611] {subprocess.py:92} INFO - [0m22:35:52  Found 5 models, 0 tests, 0 snapshots, 0 analyses, 506 macros, 0 operations, 3 seed files, 0 sources, 0 exposures, 0 metrics
[2022-08-31 22:35:52,633] {subprocess.py:92} INFO - [0m22:35:52
[2022-08-31 22:36:02,936] {subprocess.py:92} INFO - [0m22:36:02  Concurrency: 1 threads (target='dev')
[2022-08-31 22:36:02,947] {subprocess.py:92} INFO - [0m22:36:02
[2022-08-31 22:36:03,058] {subprocess.py:92} INFO - [0m22:36:03  1 of 3 START seed file PUBLIC.bookings_1 ....................................... [RUN]
[2022-08-31 22:36:05,626] {subprocess.py:92} INFO - [0m22:36:05  1 of 3 ERROR loading seed file PUBLIC.bookings_1 ............................... [[31mERROR[0m in 2.55s]
[2022-08-31 22:36:05,642] {subprocess.py:92} INFO - [0m22:36:05  2 of 3 START seed file PUBLIC.bookings_2 ....................................... [RUN]
[2022-08-31 22:36:11,916] {subprocess.py:92} INFO - [0m22:36:11  2 of 3 OK loaded seed file PUBLIC.bookings_2 ................................... [[32mINSERT 16[0m in 6.26s]
[2022-08-31 22:36:11,945] {subprocess.py:92} INFO - [0m22:36:11  3 of 3 START seed file PUBLIC.customers ........................................ [RUN]
[2022-08-31 22:36:13,929] {subprocess.py:92} INFO - [0m22:36:13  3 of 3 ERROR loading seed file PUBLIC.customers ................................ [[31mERROR[0m in 1.97s]
[2022-08-31 22:36:14,002] {subprocess.py:92} INFO - [0m22:36:14
[2022-08-31 22:36:14,007] {subprocess.py:92} INFO - [0m22:36:14  Finished running 3 seeds in 0 hours 0 minutes and 21.36 seconds (21.36s).
[2022-08-31 22:36:14,285] {subprocess.py:92} INFO - [0m22:36:14
[2022-08-31 22:36:14,298] {subprocess.py:92} INFO - [0m22:36:14  [31mCompleted with 2 errors and 0 warnings:[0m
[2022-08-31 22:36:14,370] {subprocess.py:92} INFO - [0m22:36:14
[2022-08-31 22:36:14,396] {subprocess.py:92} INFO - [0m22:36:14  [33mDatabase Error in seed bookings_1 (seeds/bookings_1.csv)[0m
[2022-08-31 22:36:14,406] {subprocess.py:92} INFO - [0m22:36:14    002002 (42710): SQL compilation error:
[2022-08-31 22:36:14,425] {subprocess.py:92} INFO - [0m22:36:14    Object 'DEMO_DBT.PUBLIC.BOOKINGS_1' already exists.
[2022-08-31 22:36:14,438] {subprocess.py:92} INFO - [0m22:36:14
[2022-08-31 22:36:14,448] {subprocess.py:92} INFO - [0m22:36:14  [33mDatabase Error in seed customers (seeds/customers.csv)[0m
[2022-08-31 22:36:14,467] {subprocess.py:92} INFO - [0m22:36:14    002002 (42710): SQL compilation error:
[2022-08-31 22:36:14,498] {subprocess.py:92} INFO - [0m22:36:14    Object 'DEMO_DBT.PUBLIC.CUSTOMERS' already exists.
[2022-08-31 22:36:14,529] {subprocess.py:92} INFO - [0m22:36:14
[2022-08-31 22:36:14,546] {subprocess.py:92} INFO - [0m22:36:14  Done. PASS=1 WARN=0 ERROR=2 SKIP=0 TOTAL=3
[2022-08-31 22:36:16,228] {subprocess.py:96} INFO - Command exited with return code 1
[2022-08-31 22:36:16,267] {taskinstance.py:1909} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 195, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-08-31 22:36:16,285] {taskinstance.py:1420} INFO - Marking task as FAILED. dag_id=1_init_once_seed_data, task_id=load_seed_data_once, execution_date=20220831T223525, start_date=20220831T223531, end_date=20220831T223616
[2022-08-31 22:36:16,324] {standard_task_runner.py:97} ERROR - Failed to execute job 3 for task load_seed_data_once (Bash command failed. The command returned a non-zero exit code 1.; 1590)
[2022-08-31 22:36:16,367] {local_task_job.py:156} INFO - Task exited with return code 1
[2022-08-31 22:36:16,429] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
